### ISSUE TITLE
hello doesn't work

### ISSUE THREAD

**Issue by chtcheglov-ilia** [nuta/resea#5] opened 2020-04-03 10:12 UTC
Running hello completely blocks the shell.
```
static error_t run_app(const char *name) {
    char path[128];
    strncpy(path, "/apps/", sizeof(path));
    strncpy(&path[6], name, sizeof(path) - 6);
	 TRACE ("AT %d", __LINE__);

    // Open the executable file.
    struct message m;
    m.type = FS_OPEN_MSG;
    m.fs_open.path = path;
    m.fs_open.len = strlen(path) + 1;
	 TRACE ("AT %d", __LINE__);
    error_t err = ipc_call(fs_server, &m);
	 TRACE ("AT %d", __LINE__);
```
My test code shows

> [shell] AT 202
> [shell] AT 209

In servers/shell/main.c at line 208
`error_t err = ipc_call(fs_server, &m);` doesn't return.

**Comment by nuta** [comment] 2020-04-04 02:10
Could you share the whole kernel log? It's not reproducible in my environment.

**Comment by nuta** [comment] 2020-06-20 07:31
Closing this issue since the implementation has been updated. Feel free to reopen if this problem still reproduces.

**Closed by nuta** 2020-06-20 07:31 UTC
